name: arifayduran_dev
description: "Portfolio, Arif Ayduran"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  rive: ^0.13.19
  shared_preferences: ^2.3.3
  transparent_image: ^2.0.1
  intl: ^0.19.0
  universal_html: ^2.2.4
  provider: ^6.1.2
  language_code: ^0.5.5
  dash_flags: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/app_icons/
    - lib/l10n/
